### ISSUE TITLE
Can more pre-trained checkpoint be provided?

### ISSUE THREAD

**Issue by YanGe1105** [UCSC-VLAA/CRATE-alpha#2]

**Comment by Rayjryang** [comment]
Hi, we have uploaded all the pre-trained torch weights of CRATE-$\alpha$ at this link: https://huggingface.co/UCSC-VLAA/CRATE-alpha/tree/main/torch/in21k_Pretrain. Hope it's useful for you.

**Comment by YanGe1105** [comment]
Thank you for your reply
